[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cfms-server-doc"
version = "0.1.0"
description = "CFMS Server Documentation"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.5.0",
    "mkdocs-material>=9.0.0",
    "mkdocstrings[python]>=0.24.0",
]

[tool.uv]
package = false